### ISSUE TITLE
CLIP(CNN)

### ISSUE THREAD

**Issue by chenpan0103** [Zoky-2020/SGA#1]
Excuse me, the existing code only gives the code about ALBEF, TCL, CLIP(VIT), I did not find CLIP(CNN), what should I do if I want to use it?

**Comment by Sammy42779** [comment]
Hello, if you want to use CLIP(CNN), directly change the "image_encoder" from "ViT-B/16" to "RN101" since we use ResNet-101 as the base architecture for the image encoder (Sec. 5.1).

**Comment by chenpan0103** [comment]
Thanks for your reply, it does work. By the way, I have one more question. How can I reproduce the results of attack methods other than SGA in the table? Only the SGA code seems to have been given
![image](https://github.com/Zoky-2020/SGA/assets/55188223/b17a98e6-dda5-4529-8741-0578832222b9)

**Comment by chenpan0103** [comment]
Sorry to bother you, it seems that the code from CLIP to TCL or ALBEF is missing. I would appreciate it if you could provide it.

**Comment by Zoky-2020** [comment]
> Thanks for your reply, it does work. By the way, I have one more question. How can I reproduce the results of attack methods other than SGA in the table? Only the SGA code seems to have been given ![image](https://user-images.githubusercontent.com/55188223/263205261-b17a98e6-dda5-4529-8741-0578832222b9.png)

We will update the related codes soon.
Here is the official repo. of Co-Attack, https://github.com/adversarial-for-goodness/Co-Attack. PGD and BERT-Attack are modified based on 'Towards Deep Learning Models Resistant to Adversarial Attacks (https://arxiv.org/abs/1706.06083)' and 'BERT-ATTACK: Adversarial Attack Against BERT Using BERT' (https://arxiv.org/abs/2004.09984), respectively. And Sep-Attack denotes the combination of PGD and BERT-Attack. All the official repositories are accessible.

**Comment by Zoky-2020** [comment]
> Sorry to bother you, it seems that the code from CLIP to TCL or ALBEF is missing. I would appreciate it if you could provide it.

Thanks for your interest in our work. The code towards clip2albef is available now; see in eval_clip-vit2albef_flickr.py

**Comment by chenpan0103** [comment]
> > Sorry to bother you, it seems that the code from CLIP to TCL or ALBEF ，is missing. I would appreciate it if you could provide it.
> 
> Thanks for your interest in our work. The code towards clip2albef is available now; see in eval_clip-vit2albef_flickr.py

Thank you very much for your efforts to update the code, looking forward to your subsequent code updates. In addition, I would appreciate it if you could upload TCL2ALBEF ，ALBEF2TCL， CLIP2CLIP in SGA first when you are free. Thanks again for your reply.
