### ISSUE TITLE
设备问题

### ISSUE THREAD

**Issue by zepengF** [Zoky-2020/SGA#2]
你好，我想问一下代码是在什么设备上跑的，单卡能跑起来吗，我试了一下跑albef2clip-vit爆显存
![image](https://github.com/Zoky-2020/SGA/assets/48851922/b5c8cf68-9ad1-436e-bbbc-401ac6e3fad6)

**Comment by Zoky-2020** [comment]
Hi,
All experiments were conducted on a single Tesla V100 GPU. For the albef2clip experiment, we set the batch_size to 8, which resulted in actual GPU memory usage of around 28GB. 
If you encounter a 'CUDA out of memory' error, consider reducing the batch size. This adjustment does not affect the experimental results.

**Comment by zepengF** [comment]
Thank you, the problem has been solved.
