### ISSUE TITLE
Python script for ALBEF to CLIP_CNN

### ISSUE THREAD

**Issue by asif-hanif** [Zoky-2020/SGA#3]
Hi,
Thank you for great work.

Could please provide script for ALBEF--to--CLIP_CNN attack.

To check transferability from ALBEF to CLIP_CNN, I replaced `target_model` from `ViT-B/16` to `RN101` in python script `eval_albef2clip-vit_flickr.py `, and i got following scores which are different from the ones reported in paper (Table 2, last column for SGA). Could you please clarify the anomaly or I missed something.

**ALBEF to CLIP-CNN**
|  | TR R@1   |  IR R@1 |
|:--  |:-- |:-- |
|Paper | 34.93  |  46.57 |
|Reproduced | 40.12 |  51.42 |

**Comment by Zoky-2020** [comment]
Hi, please ensure that you change 'CLIP_ViT' to 'CLIP_CNN' on line 275, within the eval_asr(...) function, in the eval_albef2clip-vit_flickr.py
