### ISSUE TITLE
Corss Task Transferability - python scripts

### ISSUE THREAD

**Issue by asif-hanif** [Zoky-2020/SGA#4]
Hi, thanks for the great work.
Could you please provide script (and instructions) for cross task transferability (ITR-to-IC and ITR-VG) to reproduce the results of Table-4 and Table-5 of arxive paper.
Thanks!

**Comment by HeBangYan** [comment]
I encountered the same problem, did you solve it?

**Comment by Zoky-2020** [comment]
Hi, thanks for your interest in our work.
Here are the details regarding cross-task transferability in our paper:
1. The related experiments are conducted using the MS-COCO dataset, with ALBEF as the source model;
2. For crafting adversarial example, please refer to SGA repo. (https://github.com/Zoky-2020/SGA), specifically './SGA/eval_albef2tcl_flickr.py';
3. For the evaluation of visual grounding, refer to the ALBEF repo. (https://github.com/salesforce/ALBEF/tree/main), particularly './ALBEF/Grounding.py';
4. For the evaluation of image captioning, refer to the BLIP repo. (https://github.com/salesforce/BLIP/tree/main), particularly './BLIP/train_caption.py';

**Comment by asif-hanif** [comment]
Thanks for the response.

I have reproduced results for Table 4 (Image Caption - IC). I used ALBEF model and generated adversarial images from test set of MSCOCO. I later evaluated BLIP model on the adversarial test images.

Could you please clarify which set (train or test of MSCOCO) you used for Table 5 (Visual Grounding - VG) 
It appears that visual grounding evaluation code of ALBEF is using train images.
