### ISSUE TITLE
Reproducibility of Visual Grounding Results (Table-5)

### ISSUE THREAD

**Issue by asif-hanif** [Zoky-2020/SGA#5]
Hi @Zoky-2020 
Thanks for responding to my previous issues.

I need a few clarifications regarding Table-5 results.

1) Upon inspection of Refcoco+ dataset, I found out that `refcoco+_test.json` and `refcoco+_val.json` contain paths of images from train set of MSCOCO. I created a json file consisting of paths of these train images (along with captions) and then generated adversarial images by attacking ALBEF model. 
2) Afterwards, I performed evaluation using [Grounding.py](https://github.com/salesforce/ALBEF/blob/main/Grounding.py). I ensured that dataset class loads adversarial images during evaluation by modifying image paths in `__getitem__` of [grounding.dataset.py](https://github.com/salesforce/ALBEF/blob/main/dataset/grounding_dataset.py). 

I obtained following results which are not close to the ones reported in paper. Could you please comment if I missed something while reproducing Tabe-5.

|  |  Val | TestA | TestB |
| - | - | - | - | 
| Baseline | 58.46 | 65.89 | 46.25
| Co-Attack | 54.26 | 61.80 | 43.81
| SGA (in paper) | 53.55 | 61.19 | 43.71
| SGA (reproduced) | 56.70 | 63.60 | 44.90

**Comment by Zoky-2020** [comment]
Hi.
We do have the same experimental setps as yours. I have tried possible mistaken settings but failed to reproduce the above result. Could you please provide your source code? Here is my e-mail address: wangzq_2021@outlook.com

**Comment by asif-hanif** [comment]
Thank you for the response. I will send my code on your email address today.
