### ISSUE TITLE
老师您好

### ISSUE THREAD

**Issue by alex1243423** [Zoky-2020/SGA#6]
老师，读过您的论文之后，我有一个困惑，我在我爱计算机视觉这个公众号上，看到对您的方法描述是“在迭代优化对抗图像和对抗文本的过程，该策略逐步拉远图像和文本在特征空间中的距离，从而破坏跨模态交互，达到攻击效果。”但是这个描述，我没有在您的论文中找到，可以问下您在论文的哪个部分有提到这样的描述嘛？

**Comment by Zoky-2020** [comment]
你好，感谢对我们工作的关注。
“拉远图像和文本在特征空间中的距离，从而破坏跨模态交互，达到攻击效果”，这是我们设计多模态攻击方法的基本思路，Co-Attack也是如此。该描述在论文中对应的是 Figure-2。另外，Introduction 第四段中也有类似的描述，“In detail, SGA iteratively pushes supplemental information away between two modalities with another modality as supervision to disrupt the interactions for better harmonious perturbations”

**Comment by alex1243423** [comment]
是嘞老师，但是第一句“在迭代优化对抗图像和对抗文本的过程”似乎没找到这个描述，主要是不理解为什么让图像的对抗样本远离文本的对抗样本，难道不是让图像的对抗样本远离干净的文本。

**Comment by Zoky-2020** [comment]
这和我们的任务设定有关，即同时修改图像和文本，因此，我们认为需要考虑对抗图像和对抗文本的协同作用，拉远二者在特种空间的距离，以期更好的效果。
